# Generated by Django 6.0.1 on 2026-01-11 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde actuel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisse',
                'db_table': 'caisse',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('ESPECE', 'Espèce'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=20, verbose_name='Méthode de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(limit_choices_to={'role__in': ['Rcaissier', 'Radmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='orders.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
