# Generated by Django 6.0.1 on 2026-01-11 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix unitaire')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/', verbose_name='Image du plat')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'db_table': 'plats',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=10, unique=True, verbose_name='Numéro de table')),
                ('nombre_places', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de places')),
                ('est_occupee', models.BooleanField(default=False, verbose_name='Table occupée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(blank=True, limit_choices_to={'role': 'Rtable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'tables_restaurant',
                'ordering': ['numero_table'],
            },
        ),
    ]
