# Generated by Django 6.0.1 on 2026-01-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='type_plat',
            field=models.CharField(choices=[('entree', 'Entrée'), ('principal', 'Plat principal'), ('special', 'Plat spécial'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('accompagnement', 'Accompagnement')], default='principal', max_length=20, verbose_name='Type de plat'),
        ),
    ]
