# Generated by Django 6.0.1 on 2026-01-11 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_plat_type_plat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='restaurant.tablerestaurant', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'db_table': 'paniers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.panier', verbose_name='Panier')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.plat', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Item du panier',
                'verbose_name_plural': 'Items du panier',
                'db_table': 'panier_items',
                'ordering': ['-date_ajout'],
                'unique_together': {('panier', 'plat')},
            },
        ),
    ]
