# Generated by Django 5.0.1 on 2026-01-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_panier_panieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='necessite_preparation',
            field=models.BooleanField(default=True, help_text='Décochez pour les boissons, desserts froids, etc.', verbose_name='Nécessite une préparation en cuisine'),
        ),
    ]
