# Generated by Django 5.0.1 on 2026-01-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_plat_necessite_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('qr_code_image', models.TextField(blank=True, null=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('nombre_utilisations', models.PositiveIntegerField(default=0)),
                ('dernier_scan', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='restaurant.tablerestaurant')),
            ],
            options={
                'verbose_name': 'Code QR',
                'verbose_name_plural': 'Codes QR',
                'db_table': 'qr_codes',
                'ordering': ['-date_generation'],
            },
        ),
    ]
