# Generated by Django 6.0.1 on 2026-01-11 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_PREPARATION', 'En préparation'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='État')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('serveur', models.ForeignKey(limit_choices_to={'role__in': ['Rserveur', 'Radmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Serveur')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='restaurant.tablerestaurant', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='CommandePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandeplat_set', to='orders.commande', verbose_name='Commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.plat', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Plat commandé',
                'verbose_name_plural': 'Plats commandés',
                'db_table': 'commande_plats',
                'unique_together': {('commande', 'plat')},
            },
        ),
    ]
