# Generated by Django 6.0.1 on 2026-01-11 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_commande_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Rtable', 'Rserveur', 'Radmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='serveur',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Rserveur', 'Radmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_serveur', to=settings.AUTH_USER_MODEL, verbose_name='Serveur'),
        ),
    ]
